package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.ScheduleTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildMaster'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildMaster")) {
    triggers {
        val trigger1 = find<ScheduleTrigger> {
            schedule {
                branchFilter = ""
                triggerBuild = always()
                withPendingChangesOnly = false
            }
        }
        trigger1.apply {
            enabled = false

        }
    }
}
